In [174]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [175]:
df=pd.read_csv("IMDB Dataset.csv")

In [176]:
df

review sentiment
0      One of the other reviewerrrs has mentioned tha...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [177]:
df['review']=df['review'].str.lower()

removing html tags

In [178]:
import re
    

In [179]:
def remove_html_tags(text):
    pattern=re.compile('<.*?>')
    return pattern.sub(r'', text)

In [180]:
df['review']=df['review'].apply(remove_html_tags)

In [181]:
df

review sentiment
0      one of the other reviewerrrs has mentioned tha...  positive
1      a wonderful little production. the filming tec...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically there's a family where a little boy ...  negative
4      petter mattei's "love in the time of money" is...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  i'm going to have to disagree with the previou...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

removing punctuation

In [182]:
import string

In [183]:
def remove_punctuation(input_string):
    translator= str.maketrans('','',string.punctuation)
    result_string=input_string.translate(translator)
    return result_string

In [184]:
df['review']=df['review'].apply(remove_punctuation)

In [185]:
df

review sentiment
0      one of the other reviewerrrs has mentioned tha...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [186]:
from textblob import TextBlob

In [187]:
def spell_correction(input):
    textBlob=TextBlob(input)
    result=textBlob.correct().string
    return result

In [188]:
# for i in range(0,49999):
#     p=df['review'][i]
#     df['review']=df['review'].apply(spell_correction)
#     print(i,',',end='')

In [189]:
df['review'][0]

'one of the other reviewerrrs has mentioned that after watching just 1 oz episode youll be hooked they are right as this is exactly what happened with methe first thing that struck me about oz was its brutality and unflinching scenes of violence which set in right from the word go trust me this is not a show for the faint hearted or timid this show pulls no punches with regards to drugs sex or violence its is hardcore in the classic use of the wordit is called oz as that is the nickname given to the oswald maximum security state penitentary it focuses mainly on emerald city an experimental section of the prison where all the cells have glass fronts and face inwards so privacy is not high on the agenda em city is home to manyaryans muslims gangstas latinos christians italians irish and moreso scuffles death stares dodgy dealings and shady agreements are never far awayi would say the main appeal of the show is due to the fact that it goes where other shows wouldnt dare forget pretty pict

In [190]:
# import nltk
# from nltk.tokenize import word_tokenize
# nltk.download('punkt')


# def custom_tokenizer(text):
#     tokens = word_tokenize(text)
#     # Apply additional preprocessing steps if needed
#     return tokens

In [191]:
# df['review'] = df['review'].apply(custom_tokenizer)

In [192]:
from nltk.corpus import stopwords
removing_stopwords=stopwords.words('english')

In [193]:
removing_stopwords

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [194]:

stop_words = set(stopwords.words('english'))

In [195]:
df

review sentiment
0      one of the other reviewerrrs has mentioned tha...  positive
1      a wonderful little production the filming tech...  positive
2      i thought this was a wonderful way to spend ti...  positive
3      basically theres a family where a little boy j...  negative
4      petter matteis love in the time of money is a ...  positive
...                                                  ...       ...
49995  i thought this movie did a down right good job...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  i am a catholic taught in parochial elementary...  negative
49998  im going to have to disagree with the previous...  negative
49999  no one expects the star trek movies to be high...  negative

[50000 rows x 2 columns]

In [196]:
# def remove_stopwords(text):
#         new_text=[]
#         for word in text:
#             if word in stopwords.words('english'):
#                 new_text.append('')
                
#             else:
#                 new_text.append(word)
#         x=new_text[:]
#         new_text.clear()
#         return " ".join(x)
def remove_stopwords(text):
    # Split the text into words
    words = text.split()
    
    # Filter out stopwords using list comprehension
    filtered_words = [word for word in words if word.lower() not in stop_words]
    
    # Join the filtered words into a string
    filtered_text = ' '.join(filtered_words)
    
    return filtered_text

In [197]:
df['review']=df['review'].apply(remove_stopwords)
df

review sentiment
0      one reviewerrrs mentioned watching 1 oz episod...  positive
1      wonderful little production filming technique ...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically theres family little boy jake thinks...  negative
4      petter matteis love time money visually stunni...  positive
...                                                  ...       ...
49995  thought movie right good job wasnt creative or...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  catholic taught parochial elementary schools n...  negative
49998  im going disagree previous comment side maltin...  negative
49999  one expects star trek movies high art fans exp...  negative

[50000 rows x 2 columns]

In [198]:
df

review sentiment
0      one reviewerrrs mentioned watching 1 oz episod...  positive
1      wonderful little production filming technique ...  positive
2      thought wonderful way spend time hot summer we...  positive
3      basically theres family little boy jake thinks...  negative
4      petter matteis love time money visually stunni...  positive
...                                                  ...       ...
49995  thought movie right good job wasnt creative or...  positive
49996  bad plot bad dialogue bad acting idiotic direc...  negative
49997  catholic taught parochial elementary schools n...  negative
49998  im going disagree previous comment side maltin...  negative
49999  one expects star trek movies high art fans exp...  negative

[50000 rows x 2 columns]

In [199]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['sentiment']=le.fit_transform(df['sentiment'])

In [200]:
X= df.iloc[:,:-1].values
Y= df.iloc[:,-1].values

In [201]:
df

review  sentiment
0      one reviewerrrs mentioned watching 1 oz episod...          1
1      wonderful little production filming technique ...          1
2      thought wonderful way spend time hot summer we...          1
3      basically theres family little boy jake thinks...          0
4      petter matteis love time money visually stunni...          1
...                                                  ...        ...
49995  thought movie right good job wasnt creative or...          1
49996  bad plot bad dialogue bad acting idiotic direc...          0
49997  catholic taught parochial elementary schools n...          0
49998  im going disagree previous comment side maltin...          0
49999  one expects star trek movies high art fans exp...          0

[50000 rows x 2 columns]

In [202]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(ngram_range=(1,3),max_features=10000)

In [203]:
X=cv.fit_transform(df['review']).toarray()

In [204]:
print(len(cv.vocabulary_))

10000


In [205]:
print(X[0])

[0 0 0 ... 0 0 0]


In [206]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [207]:
Y

array([1, 1, 1, ..., 0, 0, 0])

splitting data into x train and ytrain

In [208]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [209]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((40000, 10000), (10000, 10000), (40000,), (10000,))

In [210]:
from sklearn.naive_bayes import GaussianNB
classfier=GaussianNB()
classfier.fit(X_train,y_train)

GaussianNB()

In [211]:
pred= classfier.predict(X_test)

In [212]:
from sklearn.metrics import accuracy_score , classification_report, confusion_matrix
print(accuracy_score(y_test,pred))

0.8232


In [213]:
pd.DataFrame(np.c_[y_test, pred],columns=['actual','predicted'])

actual  predicted
0          1          1
1          0          0
2          0          1
3          1          1
4          1          1
...      ...        ...
9995       0          0
9996       0          0
9997       1          1
9998       1          0
9999       0          0

[10000 rows x 2 columns]

[0 0 0 ... 0 0 0]


save my traned naive-bayes and tfidf

In [249]:
input_text = ["Stephen Hawkings is a genius. He is the king of geniuses. Watching this movie makes me feel dumb. But it's a great movie. Not highly entertaining, but very very intriguing. The movie centers around wheelchair bound Stephen Hawkings, a man who makes Einstein look average, and his theories and scientific discoveries about the universe, time, the galaxy, and black holes. Everyone at sometime or another during a really intense high comes to a moment when they think they'v got the universe and the cosmos figured out and they swear as soon as they sober up they'll write it all down. Well here is a man who actually held that feeling for more then six hours. Here is a man who despite suffering from Lou Gehrig's disease has become the greatest mind the world has yet seen. Watch this and listen in on how he has formulated theories on black holes. Awesome. You won't be the same after you see it."]

input_text=cv.transform(input_text).toarray()

print(input_text)



[[0 0 0 ... 0 0 0]]


In [250]:
output= classfier.predict(input_text)
print(output)


[1]


In [251]:
def ouput_n(output):
    if output==[0]:
        print("review is negative")
        
    else:
        print('review is positive')

In [252]:
out=ouput_n(output)

review is positive
